eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false

server:
  port: 8765

zuul:
  prefix: /api
  routes:
    client:
      path: /client/**
      serviceId: service-discovery-client
    kotlin-client:
      path: /kotlin-client/**
      serviceId: service-kotlin-client

spring:
  boot:
    admin:
      url: http://localhost:8086
  profiles:
    active: production
  application:
    name: api-gateway

management:
  security:
    enabled: false
