spring:
  boot:
    admin:
      url: http://localhost:8086
  profiles:
    active: production
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false

server:
  port: ${PORT:8765}

zuul:
  prefix: /api
  routes:
    client:
      path: /prod-java-client/**
      serviceId: service-discovery-client
    kotlin-client:
      path: /prod-kotlin-client/**
      serviceId: service-kotlin-client
    order-service:
      path: /prod-order/**
      serviceId: order-service
    product-service:
      path: /prod-product/**
      serviceId: service-kotlin-client

management:
  security:
    enabled: false
