eureka:
  instance:
    metadataMap:
      region: Spain
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: ${PORT:8084}

spring:
  boot:
    admin:
      url: http://localhost:8086
  profiles:
    active: production
  application:
    name: service-kotlin-client
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: secret

management:
  security:
    enabled: false

configurable-name: Advanced service for Unicorns
