eureka:
  instance:
    metadataMap:
      region: Brazil
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

spring:
  boot:
    admin:
      url: http://localhost:8086
  profiles:
    active: production
  application:
    name: service-kotlin-client

management:
  security:
    enabled: false
