eureka:
  instance:
    metadataMap:
      region: USA
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082

spring:
  boot:
    admin:
      url: http://localhost:8086
  profiles:
    active: production
  application:
    name: service-discovery-client

management:
  security:
    enabled: false

configurable-name: Simple service for Princess
